### PR TITLE
Included RML Strategy, fixed some mistakes, and updated sources to respect RML-IO

### PR DESCRIPTION
**Pull request by chrdebru**
@anaigmo: I have removed "join" from the comment in the ontology to make `rml:Strategy` and `rml:strategy` implicitly specific to RML-CC.

### CODE REVIEW

**Comment by chrdebru** [comment]
@frmichel Can you check?

**Comment by frmichel** [comment]
Hi @chrdebru, sorry I've been away from the last discussions. I'm just confused about commit https://github.com/kg-construct/rml-cc/pull/49/commits/29216b27393ed1b1ab2a83e8fd94cd09e1b394a1, I though the plan was to move rml:Strategy to core, but it is reintegrated into CC here. Why is that?

**Comment by dachafra** [comment]
@frmichel the explanation is here https://github.com/kg-construct/rml-core/issues/51 (last comment from Ben)

**Comment by frmichel** [comment]
Ok got it, thx @dachafra, sorry for missing that.

**Comment by dachafra** [comment]
no worries! :-)

**Comment by frmichel** [comment]
Just one tiny remark, the rendered.html mentions 10 January 2024 as the spec date. This is on purpose or should be updated?
Apart from that I've good, you can merge the PR whenever you like.

**Pull request merged**
