### PR TITLE
Fixing namespaces. Changing `rr:` into `rml:` where necessary.

### PR DESCRIPTION
**Pull request by chrdebru**

### CODE REVIEW

**Review by DylanVanAssche — APPROVED** [review]

**Comment by frmichel** [comment]
Thx for this @chrdebru. Looks good to me. Only doubt, there remains the rr: namespace definition in overview.md, should we remove it or do we refer to it somewhere?

**Comment by blindreviewing** [comment]
Normally, the `rr:` namespace should be fully replaced by the `rml:` one.

**Comment by DylanVanAssche** [comment]
Normally, the namespace can be fully replaced by the RML one

**Comment by chrdebru** [comment]
I kept the one rr namespace declaration in the example as there is a section on rr:column. Rr:column is not declared in rml core.Sent from my iPhoneOn 7 Jul 2023, at 12:55, Dylan Van Assche ***@***.***> wrote:﻿
Normally, the namespace can be fully replaced by the RML one

**Comment by DylanVanAssche** [comment]
> Rr:column is not declared in rml core

`rr:column` is superseded by `rml:reference` and won't be supported anymore by Core.

**Comment by chrdebru** [comment]
Yes. But we discussed backwards compatible w.r.t. columns in our spec. We can remove the rr namespace declaration, but then it will need to be mentioned in that section.Sent from my iPhoneOn 7 Jul 2023, at 15:17, Dylan Van Assche ***@***.***> wrote:﻿

Rr:column is not declared in rml core

rr:column is superseded by rml:reference and won't be supported anymore by Core.

**Comment by DylanVanAssche** [comment]
Ah but backwards compatibility is already handled in Core for this. But @anaigmo, @andimou and @pmaria know better about this part.

**Comment by chrdebru** [comment]
I’ll remove it, then!On 7 Jul 2023, at 15:23, Dylan Van Assche ***@***.***> wrote:﻿
Ah but backwards compatibility is already handled in Core for this. But @anaigmo, @andimou and @pmaria know better about this part.

**Pull request merged**
